/* Fotos de obras: archivos en ./obras (grande) y ./obras/thumbs (miniatura) */
const OBRAS = [
    {"img": "pisco-elqui-01.jpg", "title": "Casa Pisco Elqui", "subtitle": "Ventanales de gran formato", "cat": "residencial"},
    {"img": "solar-room-01.jpg", "title": "Solar Room", "subtitle": "Estructura vidriada a medida", "cat": "especiales"},
    {"img": "eleam-la-serena-01.jpg", "title": "ELEAM La Serena", "subtitle": "Establecimiento de larga estadía", "cat": "institucional"},
    {"img": "frigorifico-el-penon-01.jpg", "title": "Frigorífico El Peñón", "subtitle": "Edificio de oficinas", "cat": "institucional"},
    {"img": "casa-residencial-01.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "muro-cortina-01.jpg", "title": "Muro Cortina", "subtitle": "Fachada vidriada industrial", "cat": "institucional"},
    {"img": "aconex-01.jpg", "title": "Edificio de Oficinas", "subtitle": "Barrio industrial", "cat": "institucional"},
    {"img": "museo-la-serena-01.jpg", "title": "Museo La Serena", "subtitle": "Restauración de ventanas", "cat": "institucional"},
    {"img": "colegio-heroes-01.jpg", "title": "Colegio Héroes de la Concepción", "subtitle": "Recambio de ventanas", "cat": "institucional"},
    {"img": "locutorio-01.jpg", "title": "Locutorio Avenida del Mar", "subtitle": "Cierre vidriado", "cat": "institucional"},
    {"img": "oficinas-01.jpg", "title": "Acceso de Oficinas", "subtitle": "Puertas y mamparas de aluminio", "cat": "institucional"},
    {"img": "cierre-terraza-01.jpg", "title": "Cierre de Terraza", "subtitle": "Cerramientos y cortinas de cristal", "cat": "especiales"},
    {"img": "casa-ovalle-01.jpg", "title": "Casa en Ovalle", "subtitle": "Proyecto residencial", "cat": "residencial"},
    {"img": "casa-morrillos-01.jpg", "title": "Casa Morrillos", "subtitle": "Proyecto residencial", "cat": "residencial"},
    {"img": "hacienda-mirador-01.jpg", "title": "Hacienda Mirador Río Limarí", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "puerta-del-sol-01.jpg", "title": "Loteo Puerta del Sol, Ovalle", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "miraflores-01.jpg", "title": "Loteo Miraflores", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "la-hacienda-01.jpg", "title": "La Hacienda", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "los-penones-01.jpg", "title": "Loteo Los Peñones, Ovalle", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "detalle-01.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "pisco-elqui-02.jpg", "title": "Casa Pisco Elqui", "subtitle": "Ventanales de gran formato", "cat": "residencial"},
    {"img": "pisco-elqui-03.jpg", "title": "Casa Pisco Elqui", "subtitle": "Ventanales de gran formato", "cat": "residencial"},
    {"img": "pisco-elqui-04.jpg", "title": "Casa Pisco Elqui", "subtitle": "Ventanales de gran formato", "cat": "residencial"},
    {"img": "solar-room-02.jpg", "title": "Solar Room", "subtitle": "Estructura vidriada a medida", "cat": "especiales"},
    {"img": "solar-room-03.jpg", "title": "Solar Room", "subtitle": "Estructura vidriada a medida", "cat": "especiales"},
    {"img": "solar-room-04.jpg", "title": "Solar Room", "subtitle": "Estructura vidriada a medida", "cat": "especiales"},
    {"img": "solar-room-05.jpg", "title": "Solar Room", "subtitle": "Estructura vidriada a medida", "cat": "especiales"},
    {"img": "solar-room-06.jpg", "title": "Solar Room", "subtitle": "Estructura vidriada a medida", "cat": "especiales"},
    {"img": "solar-room-07.jpg", "title": "Solar Room", "subtitle": "Estructura vidriada a medida", "cat": "especiales"},
    {"img": "eleam-la-serena-02.jpg", "title": "ELEAM La Serena", "subtitle": "Establecimiento de larga estadía", "cat": "institucional"},
    {"img": "eleam-la-serena-03.jpg", "title": "ELEAM La Serena", "subtitle": "Establecimiento de larga estadía", "cat": "institucional"},
    {"img": "eleam-la-serena-04.jpg", "title": "ELEAM La Serena", "subtitle": "Establecimiento de larga estadía", "cat": "institucional"},
    {"img": "eleam-la-serena-05.jpg", "title": "ELEAM La Serena", "subtitle": "Establecimiento de larga estadía", "cat": "institucional"},
    {"img": "eleam-la-serena-06.jpg", "title": "ELEAM La Serena", "subtitle": "Establecimiento de larga estadía", "cat": "institucional"},
    {"img": "eleam-la-serena-07.jpg", "title": "ELEAM La Serena", "subtitle": "Establecimiento de larga estadía", "cat": "institucional"},
    {"img": "frigorifico-el-penon-02.jpg", "title": "Frigorífico El Peñón", "subtitle": "Edificio de oficinas", "cat": "institucional"},
    {"img": "frigorifico-el-penon-03.jpg", "title": "Frigorífico El Peñón", "subtitle": "Edificio de oficinas", "cat": "institucional"},
    {"img": "frigorifico-el-penon-04.jpg", "title": "Frigorífico El Peñón", "subtitle": "Edificio de oficinas", "cat": "institucional"},
    {"img": "frigorifico-el-penon-05.jpg", "title": "Frigorífico El Peñón", "subtitle": "Edificio de oficinas", "cat": "institucional"},
    {"img": "frigorifico-el-penon-06.jpg", "title": "Frigorífico El Peñón", "subtitle": "Edificio de oficinas", "cat": "institucional"},
    {"img": "frigorifico-el-penon-07.jpg", "title": "Frigorífico El Peñón", "subtitle": "Edificio de oficinas", "cat": "institucional"},
    {"img": "casa-residencial-02.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-03.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-04.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-05.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-06.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-07.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-08.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-09.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-10.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-11.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-12.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-13.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-14.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-15.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-16.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-17.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-18.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "casa-residencial-19.jpg", "title": "Vivienda Particular", "subtitle": "Ventanas y puertas a medida", "cat": "residencial"},
    {"img": "muro-cortina-02.jpg", "title": "Muro Cortina", "subtitle": "Fachada vidriada industrial", "cat": "institucional"},
    {"img": "aconex-02.jpg", "title": "Edificio de Oficinas", "subtitle": "Barrio industrial", "cat": "institucional"},
    {"img": "museo-la-serena-02.jpg", "title": "Museo La Serena", "subtitle": "Restauración de ventanas", "cat": "institucional"},
    {"img": "colegio-heroes-02.jpg", "title": "Colegio Héroes de la Concepción", "subtitle": "Recambio de ventanas", "cat": "institucional"},
    {"img": "colegio-heroes-03.jpg", "title": "Colegio Héroes de la Concepción", "subtitle": "Recambio de ventanas", "cat": "institucional"},
    {"img": "cierre-terraza-02.jpg", "title": "Cierre de Terraza", "subtitle": "Cerramientos y cortinas de cristal", "cat": "especiales"},
    {"img": "cierre-terraza-03.jpg", "title": "Cierre de Terraza", "subtitle": "Cerramientos y cortinas de cristal", "cat": "especiales"},
    {"img": "cierre-terraza-04.jpg", "title": "Cierre de Terraza", "subtitle": "Cerramientos y cortinas de cristal", "cat": "especiales"},
    {"img": "cierre-terraza-05.jpg", "title": "Cierre de Terraza", "subtitle": "Cerramientos y cortinas de cristal", "cat": "especiales"},
    {"img": "cierre-terraza-06.jpg", "title": "Cierre de Terraza", "subtitle": "Cerramientos y cortinas de cristal", "cat": "especiales"},
    {"img": "cierre-terraza-07.jpg", "title": "Cierre de Terraza", "subtitle": "Cerramientos y cortinas de cristal", "cat": "especiales"},
    {"img": "casa-ovalle-02.jpg", "title": "Casa en Ovalle", "subtitle": "Proyecto residencial", "cat": "residencial"},
    {"img": "casa-morrillos-02.jpg", "title": "Casa Morrillos", "subtitle": "Proyecto residencial", "cat": "residencial"},
    {"img": "hacienda-mirador-02.jpg", "title": "Hacienda Mirador Río Limarí", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "hacienda-mirador-03.jpg", "title": "Hacienda Mirador Río Limarí", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "puerta-del-sol-02.jpg", "title": "Loteo Puerta del Sol, Ovalle", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "puerta-del-sol-03.jpg", "title": "Loteo Puerta del Sol, Ovalle", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "miraflores-02.jpg", "title": "Loteo Miraflores", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "miraflores-03.jpg", "title": "Loteo Miraflores", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "la-hacienda-02.jpg", "title": "La Hacienda", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "los-penones-02.jpg", "title": "Loteo Los Peñones, Ovalle", "subtitle": "Conjunto habitacional", "cat": "conjuntos"},
    {"img": "detalle-02.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "detalle-03.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "detalle-04.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "detalle-05.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "detalle-06.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "detalle-07.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "detalle-08.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
    {"img": "detalle-09.jpg", "title": "Puertas y Detalles", "subtitle": "Terminaciones a medida", "cat": "detalles"},
]
